### PR TITLE
New action

### PR DESCRIPTION
**Pull request by RafalMichalakBP**

### CODE REVIEW

**Comment by RafalMichalakBP** [comment]
<details>
<summary>Expand to view full test results for commit 8f01718fbe26e4558ce9f2bc0d2baaa305606560 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details>

**Review by RafMic — CHANGES_REQUESTED** [review]
## \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: WARNINGS SUMMARY \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
```python
 =============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
``` 
 ## \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: REVIEW WARNINGS \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:

**Comment by RafalMichalakBP** [comment]
<details>
<summary>Expand to view full test results for commit 6117df74127b65801dcd7b77bc81d27357f9963d </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details>

**Review by RafMic — CHANGES_REQUESTED** [review]
## \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: WARNINGS SUMMARY \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
```python
 =============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
``` 
 ## \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: REVIEW WARNINGS \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:

**Review by RafMic — APPROVED** [review]

**Pull request closed without merging**
