### PR TITLE
New action

### PR DESCRIPTION
**Pull request by RafalMichalakBP**

### CODE REVIEW

**Comment by RafalMichalakBP** [comment]
<details>
<summary>Expand to view full test results for commit d9b4065eabead6c5fd45694ecdf4f152af7f56d7 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.02s ========================= 
```

</details>

**Review by RafMic — CHANGES_REQUESTED** [review]
## \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: WARNINGS SUMMARY \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
```python
 =============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.02s ========================= 
``` 
 ## \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: REVIEW WARNINGS \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:

**Review by MuskularnaMatka — APPROVED** [review]
Lgtm

**Comment by RafalMichalakBP** [comment]
<details>
<summary>Expand to view full test results for commit 1cbe6ee90fbd66f84c0b953dcc37fd9579602db5 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one FAILED
test_sample.py::test_answer PASSED

=================================== FAILURES ===================================
___________________________________ test_one ___________________________________

    def test_one():
>       assert api_v1() == 1
E       assert 2 == 1
E        +  where 2 = api_v1()

test_sample.py:10: AssertionError
=============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED test_sample.py::test_one - assert 2 == 1
 +  where 2 = api_v1()
==================== 1 failed, 1 passed, 1 warning in 0.03s ==================== 
```

</details>

**Review by RafMic — CHANGES_REQUESTED** [review]
## \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: WARNINGS SUMMARY \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
```python
 =============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================ 
``` 
 ## \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: REVIEW WARNINGS \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:

**Comment by RafalMichalakBP** [comment]
<details>
<summary>Expand to view full test results for commit 4e4225753e1e8fe0b84163698f6071136feef3f8 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
```

</details>

**Review by RafMic — DISMISSED** [review]
## \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: WARNINGS SUMMARY \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: 
```python
 =============================== warnings summary ===============================
test_sample.py::test_one
  /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
    warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.01s ========================= 
``` 
 ## \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\: REVIEW WARNINGS \:warning\:\:warning\:\:warning\:\:warning\:\:warning\:\:warning\:

**Comment by RafalMichalakBP** [comment]
<details>
<summary>Expand to view full test results for commit 2c3807afd7d12ca5800109e57488cc46dfb77200 </summary>

```python
 ============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /home/rafmic/actions-runner/_work/jira-automation/jira-automation/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/rafmic/actions-runner/_work/jira-automation/jira-automation
collecting ... collected 2 items

test_sample.py::test_one PASSED
test_sample.py::test_answer PASSED

=============================== warnings summary ===============================
test_sample.py::test_one
 /home/rafmic/actions-runner/_work/jira-automation/jira-automation/test_sample.py:5: UserWarning: api v1, should use functions from v2
 warnings.warn(UserWarning('api v1, should use functions from v2'))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================= 2 passed, 1 warning in 0.02s ========================= 
```

</details>

**Pull request closed without merging**
